- name: bootstrap app server
  hosts: web
  become: yes
  vars:
    domains:
      # - {
      #     name: restskuy,
      #     domain: "restskuy.rascent.me www.restskuy.rascent.me",
      #   }
      - {
          name: "furniskuy-admin",
          domain: "furniskuy.rascent.me www.furniskuy.rascent.me",
        }
      # - {
      #     name: "boardbyte-api",
      #     domain: "boardbyte.rascent.me www.boardbyte.rascent.me",
      #   }
      # - {
      #     name: "ecoviary-api",
      #     domain: "ecoviary.rascent.me www.ecoviary.rascent.me",
      #   }
  roles:
    - web
